### ISSUE TITLE
First TextField not activated by default

### ISSUE THREAD

**Issue by ErAshu** [keepworks/KWVerificationCodeView#11]
I have gone through https://github.com/keepworks/KWVerificationCodeView/issues/6

Here you told about this but this is not working. 

Pls fix.

**Comment by kpavankotesh** [comment]
@ErAshu can you please update to latest version of the pod `0.1.8` and also check if your Toggle Keyboard option is checked? Please Refer https://github.com/keepworks/KWVerificationCodeView/issues/6#issuecomment-397962844 for further details
