### ISSUE TITLE
Storyboard issue

### ISSUE THREAD

**Issue by ErAshu** [keepworks/KWVerificationCodeView#12]
/Base.lproj/Main.storyboard: error: IB Designables: Failed to render and update auto layout status for OTPVC (oLG-hh-m7w): dlopen(KWVerificationCodeView.framework, 1): no suitable image found.  Did find:
	KWVerificationCodeView.framework: required code signature missing for 'KWVerificationCodeView.framework'

Please find the attached screenshot.
<img width="915" alt="screen shot 2018-06-15 at 7 28 00 pm" src="https://user-images.githubusercontent.com/4178384/41471835-529de246-70d2-11e8-8b2a-fe67434fc751.png">

**Comment by kpavankotesh** [comment]
Seems like some issue with your derived data. Please update the pod and follow the solutions provided here -> https://stackoverflow.com/q/40110392/2697836
