### ISSUE TITLE
swift 4 @objc inference

### ISSUE THREAD

**Issue by serge-glance** [keepworks/KWVerificationCodeView#13]
In Xcode build settings is "default" for the "Swift 3 @objc Inference" compiler code generation for swift 4.
This causes an error when building and an @objc needs to be added to the front of:
 dynamic fileprivate func textFieldDidChange(_ notification: Foundation.Notification) 
in KWTextFieldView

in order to compile.

**Comment by kpavankotesh** [comment]
Fixed in #26
