### ISSUE TITLE
How to remove all text?

### ISSUE THREAD

**Issue by kuldip-ecosmob** [keepworks/KWVerificationCodeView#16]
tired try to remove text using coding like (Ex: kwtextfieldview.text = "")

**Comment by kpavankotesh** [comment]
you can use the `kwtextfieldview.clear()` method to clear the text. Latest release 0.1.9 has this feature.

**Comment by kuldip-ecosmob** [comment]
Thank you for give me replay and my question answer
sorry but...i can't installed latest version below code is from my pod file. many times try to installed but every time i failed to install 0.1.9....now installed 0.1.5

```
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'VMS Employee' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VMS Employee
  pod 'KWVerificationCodeView'
end
```
Please give me your input or advice if i'm going to do wrong way. and help me to install version 0.1.9.
Thank You - Pavan :)

**Comment by firozkhursheed** [comment]
Please run `pod update KWVerificationCodeView`.
