### ISSUE TITLE
Cursor is in wrong place

### ISSUE THREAD

**Issue by RajChanchal** [keepworks/KWVerificationCodeView#18]
Text Size = 36
Font: Default

![simulator screen shot - iphone 6 plus - 2018-07-15 at 20 19 58](https://user-images.githubusercontent.com/7058465/42736160-683d2488-8872-11e8-91e7-66af22b71579.png)

**Comment by RajChanchal** [comment]
Never mind, the issue is resolved by the new update of this repo.
But the new repo has following issue in `KWTextFieldView.swift` file:
<img width="945" alt="screen shot 2018-07-15 at 9 00 06 pm" src="https://user-images.githubusercontent.com/7058465/42736146-1e16b7de-8872-11e8-8719-a3435b256d06.png">

**Comment by kpavankotesh** [comment]
Fixed in version `0.2.0`
