### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by HardikDG** [keepworks/KWVerificationCodeView#20]
Is there any plan to provide Carthage support to this?
I have tried to install the latest version with Carthage but it is showing error. 

Skipped building KWVerificationCodeView due to the error:
Dependency "KWVerificationCodeView" has no shared framework schemes

**Comment by kpavankotesh** [comment]
@HardikDG Thanks for your interest. We don't have support to install via Carthage yet. Feel free to add the support and create a Pull Request for the same. Thanks.
