### ISSUE TITLE
Autofill compatibility question

### ISSUE THREAD

**Issue by alexiscreuzot** [keepworks/KWVerificationCodeView#21]
Hi, I was wondering if this library works with the new iOS12 Autofill feature?
https://developer.apple.com/videos/play/wwdc2018/204/

**Comment by firozkhursheed** [comment]
Security Code AutoFill is a good option. Right now it's not supported with KWVerificationCodeView.
We would love you get a PR for this feature. It might take some time for us to add this feature.

**Comment by maulik6994** [comment]
is there any workaround to do same just for now ?

**Comment by alexiscreuzot** [comment]
I actually created my own library to handle this, as well as other things. Feel free to check it out : https://github.com/kirualex/KAPinField

**Comment by kpavankotesh** [comment]
Hey, 

We haven't got time to update this for a while. We will soon check and update the library with this feature. Will update this thread as we release the update.

**Comment by ErAshu** [comment]
any update for this?

**Comment by vishnu-pr** [comment]
Hii can you guys please add the feature any time soon

**Comment by kpavankotesh** [comment]
@ErAshu @vishnu-pr 

I'll try to implement this feature, sometime this weekend.

**Comment by vishnu-pr** [comment]
Any updates?

**Comment by ErAshu** [comment]
Hi, Any Update?

**Comment by vishnu-pr** [comment]
Hey will there be an update regarding this any time soon?

**Comment by kpavankotesh** [comment]
Hey @ErAshu @vishnu-pr,

Unfortunately, iOS doesn't support Autofill compatibility for custom inputs. Please refer the screen shot and link for details:

<img width="740" alt="Warning" src="https://user-images.githubusercontent.com/1728799/67677758-e6982d00-f9aa-11e9-92b8-42c5c181cd05.png">

https://developer.apple.com/documentation/security/password_autofill/enabling_password_autofill_on_a_text_input_view

**Comment by kpavankotesh** [comment]
When time permits, I will try to read on how some of the custom inputs handle this. Can't promise any tentative date for delivering the same.
