### ISSUE TITLE
The lib can not run on Xcode 10 swift 4.2

### ISSUE THREAD

**Issue by cuongnguyenta** [keepworks/KWVerificationCodeView#22]
Some funcs can not run on Swift 4.2 as well as: 
- UITextFieldDidChange was obsoleted on Swift 4.2
- NSLayoutFormatOptions also obsoleted.

**Comment by zsigmondszilveszter** [comment]
#24

**Comment by zsigmondszilveszter** [comment]
.

**Comment by kpavankotesh** [comment]
Fixed in #26
