### ISSUE TITLE
getVerificationCode method returns string with whitespace.

### ISSUE THREAD

**Issue by abhijithpp** [keepworks/KWVerificationCodeView#29]
getVerificationCode return string with a whitespace.

I was trying to get the count of the string returned by getVerificationCode(). It alwasy shows 1 extra count since it has a whitespace

**Comment by kpavankotesh** [comment]
@abhijithpp I tried to reproduce the issue but couldn't. Tried via IB & programatically. Can you give steps to reproduce this? 

In the mean time you can trim the whitespaces using the following code:

```swift
code.trimmingCharacters(in: CharacterSet.whitespaces)
```

**Comment by abhijithpp** [comment]
Input - 123
The method returns "123 "

PFA screenshot.

![Screen Shot 2019-06-06 at 08 36 40](https://user-images.githubusercontent.com/2706139/59015276-82779f80-8836-11e9-986c-9831e61c7cbd.png)

**Comment by kpavankotesh** [comment]
@abhijithpp if you want only 3 digits you need to set `otpTextFieldView.digits = 3` 

If you are trying to validate the code using the code count, you can use the method `otpTextFieldView.hasValidCode()` which returns `true` if all the digits are filled, `false` if there are empty fields

Check our example project for clear implementation regarding the same.
