### ISSUE TITLE
Textfield becomefirst responder

### ISSUE THREAD

**Issue by rupesh4545** [keepworks/KWVerificationCodeView#30]
I want cursor on my first textfield on viewdidload.

**Comment by rupesh4545** [comment]
public func setCursor() {
       textFieldViews[0].numberTextField.becomeFirstResponder()
    }

add this func in KWVerificationCodeView.swift

**Comment by kpavankotesh** [comment]
Added method `focus()` in latest release `v0.4.0`. Please update your pod.
