### ISSUE TITLE
Textfield touch issue

### ISSUE THREAD

**Issue by vishnu-pr** [keepworks/KWVerificationCodeView#32]
Hi, just encountered a bug in the code and wanted to bring it to your notice. If we have a OTP field which has four digit and a user click on any other textfield rather than the first one we can type into the code from there. I think it should not work like that. At first the user should only be able to touch the first field. And the last field number gets replaced every time you press any other number that also should be blocked (i think). Please look into these.

**Comment by vishnu-pr** [comment]
https://github.com/keepworks/KWVerificationCodeView/issues/31#issue-501996104 same issue
as this one expect there is one another bug in here.

**Comment by kpavankotesh** [comment]
Will be fixing this along with #31
