### ISSUE TITLE
Bug:  cannot load view in storyboard

### ISSUE THREAD

**Issue by thienthancuagio** [keepworks/KWVerificationCodeView#33]
Dear @kpavankotesh 
I  using KWVerificationCodeView in storyboard and everything is wonderful. But, sometime, I open storyboad and see the error message.
/Base.lproj/Main.storyboard: error: IB Designables: Failed to render and update auto layout status for ViewController (c58-2p-jVI): The agent threw an exception.
I check again ViewController but it  didn't show.

I see, If the storyboard reports the error above, I have to restart xcode completely. This happens intermittently when I use the storyboard

Please check the bug above

**Comment by AQElementary** [comment]
I am unable to read the code entered value by user .

**Comment by pavankotesh** [comment]
Seems like this is an issue with your derived data. Check this [SO link](https://stackoverflow.com/a/42678873)

**Comment by kpavankotesh** [comment]
Seems like this is an issue with your derived data. [Check this SO link](https://stackoverflow.com/a/42678873)

**Comment by kpavankotesh** [comment]
Seems like this is an issue with your derived data. [Check this SO link](https://stackoverflow.com/a/42678873)
