### ISSUE TITLE
Is There any option to make it 6 digits

### ISSUE THREAD

**Issue by shinto-shintzz** [keepworks/KWVerificationCodeView#4]

**Comment by kpavankotesh** [comment]
@shintoishere We are considering adding this feature in the near future.

**Comment by kpavankotesh** [comment]
Hey @shintoishere,

We've released this feature in the latest version 0.1.3. You can update your pod and use the `digits` option in storyboard to make it 6 digits

**Comment by kpavankotesh** [comment]
@shintoishere Do let us know your feedback on this update. Thanks

**Comment by shinto-shintzz** [comment]
When i install the pod old one is getting installed

**Comment by kpavankotesh** [comment]
Please try running `pod repo update`, and then try `pod install` again. CocoaPods does not automatically keep its local pod metadata up to date.

**Comment by shinto-shintzz** [comment]
tried,still the digit option is not coming

**Comment by firozkhursheed** [comment]
@shintoishere can you check the version of `KWVerificationCodeView` pod in your Podfile.lock?
It should say something like `KWVerificationCodeView (0.1.3)` in case the version for you is something different from (0.1.3) try using `pod update KWVerificationCodeView`

**Comment by shinto-shintzz** [comment]
Thanks it worked.

**Comment by firozkhursheed** [comment]
cool

**Comment by khunshan** [comment]
The property for 'digits' is not public so one cannot set it programmatically. Hilarious.

**Comment by kpavankotesh** [comment]
We've made it as IBInspectable so that user can set the value in `Storyboard` itself. We don't see a need for it to be public as of now. Is there any particular reason you need it to be public?

**Comment by khunshan** [comment]
I am creating my view programmatically. Without using xibs. But I am able to change 'digits' anyway using KVC.

**Comment by kpavankotesh** [comment]
Okay. We'll update it to `public` and make a new release so that you can use it.

**Comment by kpavankotesh** [comment]
@khunshan We've just released `v0.1.4` making all the IBInspectables `public`. Please update your pod to get these changes.
