### ISSUE TITLE
Keyboard is not minimized

### ISSUE THREAD

**Issue by nishan-p** [keepworks/KWVerificationCodeView#5]
Keyboard is not getting minimized after entering the 4th Digit. 

Can you please let me know why exactly keyboard is not minimized ??

**Comment by kpavankotesh** [comment]
@nishan-p This library was built considering there is no necessity to dismiss the keyboard, and mainly for screens similar to the one in ReadMe. If you want to dismiss the keyboard after 4th digit you can do using this boolean `hasValidCode() -> Bool ` When this is true you can do `view.endEditing()`

Note that you will have to set `isTappable` to true if you want the user to be able to re-enable the keyboard
