### ISSUE TITLE
Open keyboard on loading view

### ISSUE THREAD

**Issue by aroravaibhav** [keepworks/KWVerificationCodeView#6]
Can I open keyboard on loading my view? I don't want my user to tap on the view. The keyboard should appear to the user automatically as soon as the view gets loaded.

Thanks

**Comment by kpavankotesh** [comment]
Hey @aroravaibhav,

We released new version `0.1.5` fixing this bug. 

Opening keyboard by default on view load was the initial behaviour. This bug got introduced in one of the previous releases. Please check now and let us know.

**Comment by Mahan3340** [comment]
Hi , on Latest IOS version (11.2.6) , tested on Simulator and Iphone 6s , Keyboard is not automatically opening

**Comment by ErAshu** [comment]
Not Working even in example

**Comment by kpavankotesh** [comment]
Once you launch the simulator you have to toggle the software keyboard (in the simulator menu check `Hardware => Keyboad => Toggle Software Keyboard`). It doesn't launch by default as you have a physical keyboard connected. Run it on a device and check. It should work fine. 

Refer: https://stackoverflow.com/q/24420873/2697836

**Comment by ErAshu** [comment]
I am on iPhone not on simulator.

**Comment by nazrul-capanicus** [comment]
Yes, seems its a bug when you change the digits.
For 4 digits its working fine.
For now you can use the below method to open the keyboard and add it in `viewDidLoad()`
`self.verificationCodeView.clear()`
But its a temporally solution and Author should fix it.

**Happy coding :)**
