### ISSUE TITLE
 Keyboard Type Edit

### ISSUE THREAD

**Issue by Mahan3340** [keepworks/KWVerificationCodeView#7]
Hi , Please add a feature to be able to chagne keyboard input type ( NumberPad,ASCII, . . .)

**Comment by Mahan3340** [comment]
And there are 2 more things , the keyboard is not openning and also make textviews an option to set pasword style for them please

**Comment by kpavankotesh** [comment]
@Mahan3340 Please check release 0.1.7 for keyboardType property to edit the keyboard type programatically. 

`keyboardType` - Sets the keyboard type (Defaults to Number Pad)
