### ISSUE TITLE
Toolbar on keypad

### ISSUE THREAD

**Issue by vikasgudi** [keepworks/KWVerificationCodeView#9]
Is there any option to add tollbar to keyboard?
Please let me know, if any option exist for this ASAP.
Thanks in advance.

**Comment by vikasgudi** [comment]
Am trying to implement KWVerificationCodeView, but got stuck with this toolbar thing. 
Please let me know, if there is any solution available for this issue ASAP.

**Comment by kpavankotesh** [comment]
@vikasgudi We don't have any specific option to add toolbar to Keyboard. We use the default keyboard itself.
